apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app.kubernetes.io/name: jupyter
spec:
  containers:
  - name: jupyter
    image: jupyter/base-notebook
    ports:
    - containerPort: 8888

