apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jupyter2
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30007

